version: '3.10'
services:
  backend:
    build: ./machine_learning_client/
    expose:
      - "5000"
    networks:
      - app-network
    depends_on:
      - mongodb

  frontend:
    build: ./web-app
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - app-network
    
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    attach: false # disable logging
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
