name: machine-learning-client

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Install Python, pipenv and root Pipfile deps
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install local dependencies
        run: |
          pipenv install --dev  # or --system if you prefer plain pip
          pipenv install -r machine_learning_client/container_req.txt

      - name: Install Tesseract & Mesa
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            tesseract-ocr \
            libtesseract-dev \
            libgl1-mesa-glx

      - name: Run pytest on all tests
        run: |
          pipenv install pytest
          pipenv run pytest tests/test_client.py